"""
Workout plan generation module.

Contains prompt construction and Groq API interaction logic
for generating personalized weekly workout plans.
"""

from groq import Groq

SYSTEM_PROMPT = """You are an experienced, certified personal trainer who creates safe, 
structured, and personalized weekly workout plans.

RULES YOU MUST FOLLOW:
1. **Respect every constraint the user provides** — equipment available, days per week,
   experience level, fitness goal, and any injuries or limitations. Never suggest an exercise
   that requires equipment the user does not have. Never schedule more training days than the
   user specifies.
2. **Output format** — Return the plan in this exact Markdown structure:

   ## Weekly Workout Plan

   ### Day 1 – <Focus / Theme>
   | Exercise | Sets | Reps | Rest |
   |----------|------|------|------|
   | ... | ... | ... | ... |

   (Repeat for each training day. For rest days, simply write "### Day X – Rest Day".)

   After the table for each day, add one sentence of coaching cues or tips relevant to the
   exercises listed.

3. **Warm-up & cool-down** — Include a brief warm-up note at the top and a cool-down note
   at the bottom of the plan.
4. **Beginner-friendly language** — If the user is a beginner, briefly describe each exercise
   the first time it appears (one line).
5. **Injury / limitation handling** — If the user mentions any injury, limitation, or health
   condition:
   - Avoid all exercises that could aggravate it and suggest safe alternatives.
   - Add this disclaimer at the very end of the plan:
     > ⚠️ **Disclaimer:** This plan is generated by an AI and is not a substitute for
     > professional medical advice. Please consult a qualified healthcare provider or
     > physiotherapist before starting any exercise program, especially given your
     > mentioned limitations.
6. **No medical claims** — Never diagnose, prescribe, or promise specific health outcomes.
7. **Stay concise** — Do not add filler. Every sentence should be actionable.
"""


def build_user_prompt(
    fitness_goal: str,
    experience_level: str,
    days_per_week: int,
    equipment: list[str],
    limitations: str,
) -> str:
    """Build the user-facing prompt from structured inputs.

    Args:
        fitness_goal: The user's primary fitness goal.
        experience_level: Beginner, Intermediate, or Advanced.
        days_per_week: Number of days the user can train (1-7).
        equipment: List of equipment categories the user has access to.
        limitations: Free-text injuries or limitations (may be empty).

    Returns:
        A well-structured prompt string for the LLM.
    """
    equipment_str = ", ".join(equipment) if equipment else "No equipment (bodyweight only)"

    prompt_parts: list[str] = [
        f"**Goal:** {fitness_goal}",
        f"**Experience level:** {experience_level}",
        f"**Available training days per week:** {days_per_week}",
        f"**Equipment access:** {equipment_str}",
    ]

    if limitations and limitations.strip():
        prompt_parts.append(
            f"**Injuries / limitations:** {limitations.strip()}"
        )
    else:
        prompt_parts.append("**Injuries / limitations:** None reported.")

    prompt_parts.append(
        "\nPlease generate a complete weekly workout plan that strictly respects "
        "all of the above constraints. Use the Markdown table format described in "
        "your instructions."
    )

    return "\n".join(prompt_parts)


def generate_workout_plan(
    api_key: str,
    fitness_goal: str,
    experience_level: str,
    days_per_week: int,
    equipment: list[str],
    limitations: str,
    model: str = "openai/gpt-oss-20b",
) -> str:
    """Call the Groq API and return a workout plan.

    Args:
        api_key: Groq API key.
        fitness_goal: The user's primary fitness goal.
        experience_level: Beginner, Intermediate, or Advanced.
        days_per_week: Number of days the user can train (1-7).
        equipment: List of equipment categories the user has access to.
        limitations: Free-text injuries or limitations (may be empty).
        model: Groq model identifier.

    Returns:
        The generated workout plan as a Markdown string.

    Raises:
        ValueError: If the API returns an empty or malformed response.
        Exception: Propagates API / network errors for the caller to handle.
    """
    user_prompt = build_user_prompt(
        fitness_goal=fitness_goal,
        experience_level=experience_level,
        days_per_week=days_per_week,
        equipment=equipment,
        limitations=limitations,
    )

    client = Groq(api_key=api_key)

    chat_completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.7,
        max_tokens=4096,
    )

    # Validate the response
    if (
        not chat_completion
        or not chat_completion.choices
        or not chat_completion.choices[0].message
        or not chat_completion.choices[0].message.content
    ):
        raise ValueError(
            "The AI returned an empty or malformed response. Please try again."
        )

    return chat_completion.choices[0].message.content.strip()


def swap_exercise(
    api_key: str,
    exercise_name: str,
    context: str,
    model: str = "openai/gpt-oss-20b",
) -> str:
    """Ask the LLM to suggest an alternative for a single exercise.

    Args:
        api_key: Groq API key.
        exercise_name: The exercise the user wants to swap.
        context: The full workout plan (for context on equipment & constraints).
        model: Groq model identifier.

    Returns:
        A short suggestion for an alternative exercise.
    """
    swap_prompt = (
        f"Given the following workout plan:\n\n{context}\n\n"
        f'The user wants to swap out **"{exercise_name}"** for a suitable '
        f"alternative that respects the same equipment and limitation constraints. "
        f"Respond with ONLY the replacement exercise name, sets, reps, rest, "
        f"and a one-sentence explanation of why it is a good swap. Keep it concise."
    )

    client = Groq(api_key=api_key)

    chat_completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": "You are a helpful personal trainer assistant."},
            {"role": "user", "content": swap_prompt},
        ],
        temperature=0.8,
        max_tokens=300,
    )

    if (
        not chat_completion
        or not chat_completion.choices
        or not chat_completion.choices[0].message
        or not chat_completion.choices[0].message.content
    ):
        raise ValueError("Could not generate an alternative exercise. Please try again.")

    return chat_completion.choices[0].message.content.strip()
